site_name: whitecanvas
site_description: A type safe and backend independent plotting library for Python.
repo_name: whitecanvas
repo_url: https://github.com/hanjinliu/whitecanvas

copyright: Copyright (c) 2023 - 2024 Hanjin Liu

theme:
  name: material
  features:
    - content.code.annotate
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.share
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Overview: index.md
  - Quick Start: quick_start.md
  - Canvas:
    - Overview: canvas/index.md
    - Basics: canvas/basics.md
    - Namespaces: canvas/namespaces.md
    - Canvas Grid: canvas/grid.md
    - Joint Grid: canvas/joint_grid.md
    - Legend for the Layers: canvas/legend.md
    - Working with the Backend Objects: canvas/native_objects.md
  - Layers:
    - Overview: layers/index.md
    - Lines: layers/lines.md
    - Markers: layers/markers.md
    - Distribution: layers/distribution.md
    - Texts: layers/texts.md
    - Bars, Band and Spans: layers/face_layers.md
    - Layer Groups: layers/layer_groups.md
    - Mouse Interactivity: layers/mouse.md
  - Categorical Plot:
    - Overview: categorical/index.md
    - Numerical &times; Numerical Data: categorical/num_num.md
    - Categorical &times; Numerical Data: categorical/cat_num.md
    - Categorical &times; Categorical Data: categorical/cat_cat.md
    - Aggregation: categorical/aggregation.md
    - Stacking: categorical/stacking.md
  - Event Handling:
    - Overview: events/index.md
    - Canvas Events: events/canvas_events.md
    - Layer Events: events/layer_events.md
    - Mouse Events: events/mouse_events.md
  - API Reference:
    - api/core.md
    - api/canvas.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
          options:
            docstring_style: numpy
            show_source: true
            show_bases: false
            show_signature_annotations: true
  - gen-files:
      scripts:
        - docs/_scripts/_screenshots.py

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

hooks:
  - docs/_scripts/_hooks.py

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
